{% set name = "grace-tensorpotential" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tensorpotential/tensorpotential-{{ version }}.tar.gz
  sha256: ea997d607d58e3249c89507c182a49a2ea06f26c35aa6776ac9f75315320c4e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - tf_keras
    - python >={{ python_min }}
    - scipy
    - tensorflow <2.20
    - tf-keras
    - matscipy
    - numpy <3.0.0
    - sympy
    - pandas <3.0.0
    - ase
    - pyyaml >=6.0.2
    - tqdm

test:
  imports:
    - tensorpotential
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ICAMS/grace-tensorpotential
  summary: Graph Atomic Cluster Expansion (GRACE)
  license: ASL
  license_file: ASL.txt

extra:
  recipe-maintainers:
    - jan-janssen
