{% set name = "grace-tensorpotential" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tensorpotential/tensorpotential-{{ version }}.tar.gz
  sha256: 7745dcc93618f29390e371eebb2768a7f620827cb20343766b29d0e02ad79a93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }},<3.12
    - scipy
    - tensorflow <2.17
    - matscipy
    - numpy
    - sympy
    - pandas <3.0.0
    - ase
    - pyyaml >=6.0.2
    - tqdm

test:
  imports:
    - tensorpotential
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ICAMS/grace-tensorpotential
  summary: Graph Atomic Cluster Expansion (GRACE)
  license: GPL-2.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
